# Generated by Django 3.0.6 on 2020-06-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200601_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='post',
        ),
    ]
