# Generated by Django 3.0.6 on 2020-06-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200601_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='stories_img'),
        ),
    ]
