# Generated by Django 3.0.6 on 2020-06-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_story_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
