# Generated by Django 3.0.6 on 2020-06-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='filee',
            field=models.FileField(blank=True, null=True, upload_to='stories_files'),
        ),
    ]
