# Generated by Django 3.0.6 on 2020-06-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_story_filee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='filee',
            field=models.FileField(blank=True, null=True, upload_to='stories_videos'),
        ),
    ]
