# Generated by Django 3.0.6 on 2020-06-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('typee', models.CharField(max_length=1)),
                ('time', models.CharField(max_length=1)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
