# Generated by Django 3.0.6 on 2020-06-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_story_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='comments',
        ),
    ]
